### PR TITLE
Persist-chain

### PR DESCRIPTION
**Pull request by t0rbik**
This PR makes it so that if you come with chain id in your search param it will persist it across pages so that before you connect your wallet you can already see this chain specific data.
Next idea I have is instead of rainbow kit chain switch, use hand-crafted chain switch that sends user as a link to route page with desired chain-id. This is worse UX, but it should fix the web worker issue, because when page reloads existing web worker will get terminated.

### CODE REVIEW

**Comment by oxSaturn** [comment]
It could be a nightmare when we have many links, i.e., we'll have to take care of the queries for every links.

Shall we update the query in url once network changed?

CleanShot-nIo0bLer@2x


btw, I would really hope they can expose the network switcher without connected https://github.com/rainbow-me/rainbowkit/discussions/381#discussioncomment-2983189

**Comment by t0rbik** [comment]
I didn't quite catch what you mean about query for every link? It is already added to every link. But we need a way to:
1. show data and start sdk with pre-defined in url link.
2. switch chain with page reload to properly restart sdk and sdk should start with predefined link when switching chain (basically point 1).

Unfortunately, I don't see other way of handling web worker after chain switches. I see that it still shows as only one worker running, but for some reasons it starts syncing every chain user visited

**Comment by oxSaturn** [comment]
> I didn't quite catch what you mean about query for every link? It is already added to every link. But we need a way to:
> 
> 1. show data and start sdk with pre-defined in url link.
> 2. switch chain with page reload to properly restart sdk and sdk should start with predefined link when switching chain (basically point 1).
> 
> Unfortunately, I don't see other way of handling web worker after chain switches. I see that it still shows as only one worker running, but for some reasons it starts syncing every chain user visited

ah right, didn't notice that Link was a customized one already. nice.

**Review by oxSaturn — DISMISSED** [review]

**Comment by oxSaturn** [comment]
> I didn't quite catch what you mean about query for every link? It is already added to every link. But we need a way to:
> 
> 1. show data and start sdk with pre-defined in url link.
> 2. switch chain with page reload to properly restart sdk and sdk should start with predefined link when switching chain (basically point 1).
> 
> Unfortunately, I don't see other way of handling web worker after chain switches. I see that it still shows as only one worker running, but for some reasons it starts syncing every chain user visited

So we still have this problem that the sdk won't restart when chain switched, right?

**Comment by t0rbik** [comment]
With the merge of this PR we will still have the problem, yeah. Idea is manual chain switch with page reload like 
'switchChain => {
switchChain(requestedChainId)
navigateTo(base/?chain=requestedChain, withReload)
}'

**Comment by t0rbik** [comment]
Apparently in preview now going to ?chain=someotherchain with connected wallet doesn't switch chain to some other chain

**Comment by t0rbik** [comment]
> btw, I would really hope they can expose the network switcher without connected [rainbow-me/rainbowkit#381 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/381#discussioncomment-2983189)

https://github.com/rainbow-me/rainbowkit/pull/1601#issuecomment-1858205557

**Comment by oxSaturn** [comment]
> > btw, I would really hope they can expose the network switcher without connected [rainbow-me/rainbowkit#381 (comment)](https://github.com/rainbow-me/rainbowkit/discussions/381#discussioncomment-2983189)
> 
> [rainbow-me/rainbowkit#1601 (comment)](https://github.com/rainbow-me/rainbowkit/pull/1601#issuecomment-1858205557)

I believe I've tryied before, and it won't work with the current rainbowkit.

**Comment by t0rbik** [comment]
Do you know if any other wallet management package exposes this stuff? I reckon we might need to step away from rainbow for graphene due to these sdk ways

**Comment by oxSaturn** [comment]
> Do you know if any other wallet management package exposes this stuff? I reckon we might need to step away from rainbow for graphene due to these sdk ways

None of them as far as I can remember when I was researching last time. Probably we just can manage with just wagmi. Rainbowkit is mostly just a wrapper.

**Comment by t0rbik** [comment]
Here's a flow I'm trying to build:
1. Wallet is not connected without search.chainId.
User comes to app without search.chainId, app should fetch data for default chain set in config (currently Base).
1.1 User connects wallet being on chain other than data fetching chain -> should sync wallet with data fetching chain by switching chain.
1.2 User connects wallet on same chain -> do nothing.

2. Wallet connected without search.chainId.
User comes to app without search.chainId, app should fetch data for default chain and sync user wallet by switching chain (if user is connected to other than data fetching chain).

3. Wallet is not connected with search.chainId
User comes to app, app should set data fetch chain to chain with chainId from search.
3.1 User connects and wallet should be synced with data fetch chain.
1.2 look above

4. Wallet connected with search.chainId
User comes to app, app should set data fetch chain to chain with chainId and sync wallet by switching chain if needed.

We can also set autoconnect to false, but i don't think it is needed, have to think about it more.

**Comment by t0rbik** [comment]
Requesting review just for overhead looking into it. However, it needs a solution for deep links to pair. Currently, chainId in search would get overlooked. Looking into it.

**Comment by t0rbik** [comment]
Actually looks like chainId works for deep links to exact trade pairs. 
example: https://carbon-app-git-feat-persist-chain-cre8r.vercel.app/trade?base=0xa813e24274D7F5ec2b2F9248fC50cc57D3782De3&quote=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&chainId=1

**Comment by t0rbik** [comment]
Please note that in latest commit I disabled access to app if the user connected to chain that is not the same as data fetching chain, because on metamask for example this can lead to transaction on wrong chain. This is also coherently to what original app does with being connected to unsupported chain (no access).
There is another way to prevent this which is find all actions and add this check there, but this something, i reckon, we can add later.

**Review by oxSaturn — COMMENTED** [review]
CleanShot-Iq9QzU6t@2x

Probably hide it on mobile?

CleanShot-ZVjbBLtf@2x

And probably move up the modal a little?

**Comment by t0rbik** [comment]
Screenshot 2023-12-24 at 12 04 00 pm
Screenshot 2023-12-24 at 12 03 44 pm

Believe such mobile modals are desired since it is original modal design

**Review by oxSaturn — APPROVED** [review]

**Pull request merged**
