### PR TITLE
Graphene wagmi

### PR DESCRIPTION
**Pull request by t0rbik**
This is in case we decide to use wagmi instead of web3-react

### CODE REVIEW

**Review by oxSaturn — APPROVED** [review]
Looks good, probably try dark theme for connect button https://www.rainbowkit.com/docs/theming

**Comment by t0rbik** [comment]
Wyt about ethers?

**Comment by oxSaturn** [comment]
> Wyt about ethers?

yeah, probably get rid of it as well since I don't see it used in many places.

**Comment by t0rbik** [comment]
ha That's why i havent merged it yet.. Not sure how to manage upstream. Well, tbh this wagmi update is quite granular and with updates i dont expect some huge merge conflicts. But if we remove ethers, might be harder..

**Comment by t0rbik** [comment]
It looks like to make it omni chain we would still need lots of changes

**Pull request closed without merging**
